import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    config: "src/config.ts",
    "types/index": "src/types/index.ts",
    "security/index": "src/security/index.ts",
    "middleware/index": "src/middleware/index.ts",
    version: "src/version.ts",
    "data/content-pages": "src/data/content-pages.ts",
    "data/entities": "src/data/entities.ts",
    "data/reviews": "src/data/reviews.ts",
    "data/categories": "src/data/categories.ts",
    "data/media": "src/data/media.ts",
    "data/forms": "src/data/forms.ts",
    "data/site-settings": "src/data/site-settings.ts",
    "data/activity-log": "src/data/activity-log.ts",
    "data/error-log": "src/data/error-log.ts",
    "data/affiliates": "src/data/affiliates.ts",
    "data/certifications": "src/data/certifications.ts",
    "data/cta-blocks": "src/data/cta-blocks.ts",
    "data/listicles": "src/data/listicles.ts",
    "data/redirects": "src/data/redirects.ts",
    "data/ai-conversations": "src/data/ai-conversations.ts",
    "data/internal-links": "src/data/internal-links.ts",
    "data/link-checker": "src/data/link-checker.ts",
    "ai/index": "src/ai/index.ts",
    "components/admin/index": "src/components/admin/index.ts",
    "components/ui/index": "src/components/ui/index.ts",
    "components/theme/index": "src/components/theme/index.ts",
    "components/theme/server": "src/components/theme/server.ts",
    "components/tracking/index": "src/components/tracking/index.ts",
    "utils/index": "src/utils/index.ts",
    "utils/validation": "src/utils/validation.ts",
    registry: "src/registry.ts",
    "data/api-usage": "src/data/api-usage.ts",
    "types/hub": "src/types/hub.ts",
    "data/hub-properties": "src/data/hub-properties.ts",
    "data/hub-users": "src/data/hub-users.ts",
    "data/hub-activity": "src/data/hub-activity.ts",
    "data/hub-groups": "src/data/hub-groups.ts",
    "types/admin": "src/types/admin.ts",
    "data/hub-admin": "src/data/hub-admin.ts",
    "types/projects": "src/types/projects.ts",
    "data/projects": "src/data/projects.ts",
    "data/project-parsers": "src/data/project-parsers.ts",
    "components/projects/index": "src/components/projects/index.ts",
    "types/hub-package-deployments": "src/types/hub-package-deployments.ts",
    "types/hub-marketing": "src/types/hub-marketing.ts",
    "data/hub-package-deployments": "src/data/hub-package-deployments.ts",
    "data/hub-marketing": "src/data/hub-marketing.ts",
    "types/agent": "src/types/agent.ts",
    "types/social": "src/types/social.ts",
    "data/hub-agents": "src/data/hub-agents.ts",
    "data/hub-social": "src/data/hub-social.ts",
    "types/playbooks": "src/types/playbooks.ts",
    "data/hub-playbooks": "src/data/hub-playbooks.ts",
    "types/hub-brand-assets": "src/types/hub-brand-assets.ts",
    "types/hub-content-pipeline": "src/types/hub-content-pipeline.ts",
    "types/hub-brand-setup": "src/types/hub-brand-setup.ts",
    "types/hub-qa": "src/types/hub-qa.ts",
    "types/hub-link-building": "src/types/hub-link-building.ts",
    "types/hub-marketing-ops": "src/types/hub-marketing-ops.ts",
    "types/hub-marketing-playbooks": "src/types/hub-marketing-playbooks.ts",
    "data/hub-brand-assets": "src/data/hub-brand-assets.ts",
    "data/hub-content-pipeline": "src/data/hub-content-pipeline.ts",
    "data/hub-brand-setup": "src/data/hub-brand-setup.ts",
    "data/hub-qa": "src/data/hub-qa.ts",
    "data/hub-link-building": "src/data/hub-link-building.ts",
    "data/hub-marketing-ops": "src/data/hub-marketing-ops.ts",
    "data/hub-marketing-playbooks": "src/data/hub-marketing-playbooks.ts",
    "data/hub-skill-contract": "src/data/hub-skill-contract.ts",
    "error-logging/index": "src/error-logging/index.ts",
    "error-logging/server": "src/error-logging/server.ts",
    "types/promptkit": "src/types/promptkit.ts",
    "promptkit/models": "src/promptkit/models.ts",
    "promptkit/skills": "src/promptkit/skills/index.ts",
    "promptkit/optimizers": "src/promptkit/optimizers/index.ts",
    "data/promptkit-history": "src/data/promptkit-history.ts",
    "admin/index": "src/admin/index.ts",
    "admin/types": "src/admin/types.ts",
    "admin/adapters": "src/admin/adapters.ts",
    "admin/rbac": "src/admin/rbac.ts",
    "admin/services": "src/admin/services.ts",
    "admin/hooks": "src/admin/hooks.ts",
  },
  format: ["esm"],
  dts: true,
  clean: true,
  splitting: true,
  treeshake: true,
  external: [
    "react",
    "react-dom",
    "next",
    "next/navigation",
    "next/link",
    "next/server",
    "@supabase/supabase-js",
    "@supabase/ssr",
    "@anthropic-ai/sdk",
    "tailwindcss",
    "zod",
    "class-variance-authority",
    "lucide-react",
    "react-router-dom",
  ],
  // Tsup 8.x strips "use client" from bundled outputs. Re-add it for
  // client-only entries so Next.js can import them from Server Components.
  onSuccess: "node scripts/post-build.mjs",
  // "use client" directives are in source files where needed (components).
  // Don't add a global banner — data/config modules run server-side.
});
