import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    config: "src/config.ts",
    "types/index": "src/types/index.ts",
    "security/index": "src/security/index.ts",
    "middleware/index": "src/middleware/index.ts",
    version: "src/version.ts",
    "data/content-pages": "src/data/content-pages.ts",
    "data/entities": "src/data/entities.ts",
    "data/reviews": "src/data/reviews.ts",
    "data/categories": "src/data/categories.ts",
    "data/media": "src/data/media.ts",
    "data/forms": "src/data/forms.ts",
    "data/site-settings": "src/data/site-settings.ts",
    "data/activity-log": "src/data/activity-log.ts",
    "data/error-log": "src/data/error-log.ts",
    "data/affiliates": "src/data/affiliates.ts",
    "data/certifications": "src/data/certifications.ts",
    "data/cta-blocks": "src/data/cta-blocks.ts",
    "data/listicles": "src/data/listicles.ts",
    "data/redirects": "src/data/redirects.ts",
    "data/ai-conversations": "src/data/ai-conversations.ts",
    "data/internal-links": "src/data/internal-links.ts",
    "data/link-checker": "src/data/link-checker.ts",
    "ai/index": "src/ai/index.ts",
    "components/admin/index": "src/components/admin/index.ts",
    "components/ui/index": "src/components/ui/index.ts",
    "components/theme/index": "src/components/theme/index.ts",
    "components/tracking/index": "src/components/tracking/index.ts",
    "utils/index": "src/utils/index.ts",
    registry: "src/registry.ts",
    "data/api-usage": "src/data/api-usage.ts",
    "types/hub": "src/types/hub.ts",
    "data/hub-properties": "src/data/hub-properties.ts",
    "data/hub-users": "src/data/hub-users.ts",
    "data/hub-activity": "src/data/hub-activity.ts",
    "data/hub-groups": "src/data/hub-groups.ts",
    "types/projects": "src/types/projects.ts",
    "data/projects": "src/data/projects.ts",
    "data/project-parsers": "src/data/project-parsers.ts",
    "components/projects/index": "src/components/projects/index.ts",
  },
  format: ["esm"],
  dts: true,
  clean: true,
  splitting: true,
  treeshake: true,
  external: [
    "react",
    "react-dom",
    "next",
    "next/navigation",
    "next/link",
    "next/server",
    "@supabase/supabase-js",
    "@supabase/ssr",
    "@anthropic-ai/sdk",
    "tailwindcss",
    "zod",
    "class-variance-authority",
    "lucide-react",
  ],
  // "use client" directives are in source files where needed (components).
  // Don't add a global banner — data/config modules run server-side.
});
