// AUTO-GENERATED by scripts/sync-cms-config.mjs — do not edit by hand.
// Default committed state: null sentinel. The build script overwrites this
// file with live Hub data when HUB_SUPABASE_URL + HUB_SUPABASE_ANON_KEY are
// set; otherwise cms.config.ts falls back to its hardcoded defaults.

export const HUB_ENABLED_MODULES: readonly string[] | null = null;
export const HUB_GENERATED_AT: string | null = null;
