// AUTO-GENERATED by scripts/sync-cms-config.mjs — do not edit by hand.
// Source: Pandotic Hub property 'pandotic-site' enabled_modules.
// To refresh: `pnpm sync-cms-config` (pulls latest from Hub).

export const HUB_ENABLED_MODULES: readonly string[] | null = null;
export const HUB_GENERATED_AT: string | null = null;
