[build]
  command = "cd ../.. && pnpm install && pnpm --filter @pandotic/pandotic-site... build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  NODE_OPTIONS = "--max-old-space-size=4096"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
